# This is the network config written by 'subiquity'
network:
  ethernets:
    ens4:
      addresses: [10.11.122.2/30]
      gateway4: 10.11.122.1
    ens5:
      addresses: [10.12.122.2/30]
      gateway4: 10.12.122.1
    ens6:
      addresses: [10.13.122.2/30]
      gateway4: 10.13.122.1
    ens7:
      addresses: [10.122.221.1/30]
    ens8:
      addresses: [10.122.222.1/30]
  bridges:
    dummy0:
      addresses: [192.168.3.122/32]
  version: 2